name: Deno CI

on: [push, pull_request]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
        
      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Install build tooling
        run: npm install
      
      - name: Run Tests
        run: npm run test:deno
