name: Deno CI

on: [push, pull_request]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        with:
          deno-version: "v1.x"
        
      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Install Lerna and build tooling
        run: npm install
      
      - name: Run Tests
        run: npm run test:deno
